### ISSUE TITLE
Hardware setup issue 

### ISSUE THREAD

**Issue by fif10** [aceindy/Duepi_EVO#3]
Hello 

Thank you for this great project. 
I am trying to use it  with my stove, but I am having some issues ... on the hardware part. 

I have those one 
- NodeMcu V3 4MB flash ESP8266 12E
- TXB0104 Bi-Directional Level Shifter
with a evacalor stove (PUNTO FUOCO Nelly 9.5 kw + duepi)

So far, I managed to flash the NodeMCU, connect it on wifi, (setup the custom_component on ha.)
On the hardware part I plugged it like this 

![image](https://user-images.githubusercontent.com/5849803/104704856-74c81280-5719-11eb-9018-d38867934edf.png)

The issue is that if I plug it with the stove, I get the 5V output, but nothing at the output of the level shifter where I should get the 3V.
I also tried to plug the nodeMCU with usb, I get the 3V output, but not the 5V on the level shifter. I guess that it should work as the level shifter is bi-directional
I try also by pluging the OE pin to the low level (3v). still the same...
Did I miss or misunderstood something ? Could you confirm that my setup is ok ? or should I buy and try with another level shifter ... 

Also do I need to configure any thing on esplink for the pin assigment to set the serial pin TX/RX  ?
Once plugged, is there some command I can run directly on esplink console to validate setup ? 
If I send \x1bRD90005f& for instance, should I see the result in the esp console directly ? 

Thanks a lot

**Comment by aceindy** [comment]
Hi fif10,

I basically have it like this:
![image](https://user-images.githubusercontent.com/94692/106038081-c4beb600-60d7-11eb-90b0-c45764c7df4b.png)
this is a default setup.
![image](https://user-images.githubusercontent.com/94692/106044510-1d924c80-60e0-11eb-9453-19a32ae674c7.png)

In ESPLink i use the default config:
![image](https://user-images.githubusercontent.com/94692/106038209-f59eeb00-60d7-11eb-8b3f-74efbc421483.png)

And it the console I can see each transmitted command passing by:
![image](https://user-images.githubusercontent.com/94692/106044376-f3d92580-60df-11eb-90b1-358f261a750e.png)

**Comment by aceindy** [comment]
I furthermore believe this has not much to do with Duepi Evo stoves

It sounds more like you have issues with getting ESP-Link working.
Maybe it is better to ask for support [there](https://github.com/jeelabs/esp-link)?

**Comment by fif10** [comment]
Thanks a lot for all the info. That's what I needed.
I will try with another harware devices.
