### ISSUE TITLE
How to get the new sensors in Home Assistant 

### ISSUE THREAD

**Issue by Basfoppele** [aceindy/Duepi_EVO#31]
I was wondering how to get the new sensors in Home Assistant?  

"Flug_gas_temp"
"Exh_fan_speed"
"error_code"

Thanks for the good work 👍

**Comment by aceindy** [comment]
see previous post

https://github.com/aceindy/Duepi_EVO/issues/30#issuecomment-1509359840

**Comment by aceindy** [comment]
see previous post

https://github.com/aceindy/Duepi_EVO/issues/30#issuecomment-1509359840

**Comment by Basfoppele** [comment]
Thank you very much!
