### ISSUE TITLE
connected status/off

### ISSUE THREAD

**Issue by bozzo12** [aceindy/Duepi_EVO#33]
hello, I'm finishing an ESPhome, based on wemos mini D1 and a level shutter, I think I'm ready to get it to work, the esp communicates with homeassitant, but I don't have any feedback from the stove when I start it manually, nor change the status of the stove when I change to homeassistant.
I also don't know what I should do from the code

log:
   default: warn
   logs:
     custom_components.duepi_evo: debug

sorry, I'm not very good with code, and just discovering HA

**Comment by aceindy** [comment]
Tried switching tx/rx ?

I just helped someone this weekend setting up a Wemos...maybe he can help (pls contact us on https://t.me/duepistove)
