### ISSUE TITLE
Centrometal serial protocol?

### ISSUE THREAD

**Issue by kentaur9** [aceindy/Duepi_EVO#37]
Have you been able to integrate to centrometal serial interface? Do you have some details on the protocol it uses?

**Comment by aceindy** [comment]
Centrometal? Is that a brand or what ?
My stove uses a Duepi Evo module, which can communicate with an optional wifi module.
I have replaced the wifi module with an esp-link module (lan2ser)

**Comment by pascaltippelt** [comment]
The Centrometal Z6 looks like my Wamsler Pellet-Stove. They _should_ use the same Duepi Evo board. Best way to find out: Open the right cover AFTER unplugging the power supply. If something like this is inside, you should be lucky https://larel.com/b2b/en/control-system-board/801-14710080.html:

**Comment by aceindy** [comment]
And the initial protocol is described here https://github.com/aceindy/Duepi_EVO/blob/main/InterstoveRemoteCmd.pdf

In the meantime we found a lot more...
