### ISSUE TITLE
Information: IR protocoll reverse-engineered

### ISSUE THREAD

**Issue by pascaltippelt** [aceindy/Duepi_EVO#4]
I reverse-eingneered the IR-protocoll for the stoves bases on the duepi evo line. Maybe we should cross-reference each other to help searching users. 

[Wamsler-IR-Remote](https://github.com/pascaltippelt/Wamsler-IR-Remote)

**Comment by aceindy** [comment]
Awesome work dude..

Not sure if I can use any of it though...as serial uses commands with reply (2 way communication).

I just acquired a serial2wifi module myself as the reverse engineered code from the French guy is incomplete...
Hope I can extract the missing data soon 🥼

**Comment by pascaltippelt** [comment]
The WiFi-Module ist ESP8266-based, at least the one I had in my hands. Maybe you can extract a firmware. If so, I would really be interested in a firmware dump, to analyze it.

**Comment by aceindy** [comment]
@pascaltippelt I’ll try to have a look (there is just one thing i lack....time to do it 🤔)

**Comment by pascaltippelt** [comment]
A Firmware dump, maybe done by ESP Tools, could help, as we both could work on it! 

But yes, I do understand your time related problem.

**Comment by aceindy** [comment]
@pascaltippelt 
Hmm...just opened the unit to have a peek..
It doesn't look like it uses ESP8266 based, but Motorola [RN1723-I/RM](http://ww1.microchip.com/downloads/en/DeviceDoc/70005224A.pdf)
Not sure if I can dump the firmware as easily as ESP....

**Comment by pascaltippelt** [comment]
Interesting! So there are at least 2 models around. Could you send me a picture of the pcb?

Does your WiFi module look like this one:
![Wamsler WiFi](https://image.hagebau.de/web_detail/wifi-kit-fuer-pelletofen-quattro-6--1000000000089062.jpg)

**Comment by pascaltippelt** [comment]
This might help you: https://community.jeedom.com/uploads/short-url/sKZlW8B589uAbgUrlz34R7y4veZ.pdf - it is in french, but there are some information about the interface and some commands.

**Comment by aceindy** [comment]
Yea, outside looks the same
![795CCC1C-826A-40E8-8894-FC8732685A0B](https://user-images.githubusercontent.com/94692/106364319-67707200-632e-11eb-9f7c-5d3ee9a6acca.jpeg)

**Comment by pascaltippelt** [comment]
Oh wow, definetely a complete different pcb. Mine was way more complex, and contained of cause a different microcontroller. Hope you are successfull!

**Comment by pascaltippelt** [comment]
Coult you point out wich pin is 5V, TX, RX, GND? Maybe at the PCB and at the end of the wire (4-pin-connector to stove)? Would be great!

**Comment by aceindy** [comment]
1 = White Colour ground

2 = Orange RX

3 = Red TX

4 = Violet +5Volt

**Comment by pascaltippelt** [comment]
I expected something like that. 

I am currently working on a ESP-01S based as simple as possible solution to connect to the stove (via serial). At the moment there are only 2 NPN transistors, a line voltage regulator and some resistors and capacitors required. I will update my work as soon as I have anything new to tell.

**Comment by aceindy** [comment]
![0048C55B-2002-4D55-8342-2F8C3CE5DEB1](https://user-images.githubusercontent.com/94692/107563104-f740d680-6be0-11eb-8977-1ddd81edec1b.jpeg)
Got mine from banggood 😉

**Comment by pascaltippelt** [comment]
Exactly. But I need some more IO, so I develop myself ;-)

**Comment by pascaltippelt** [comment]
I just first time successfully turned the stove off by telnet, using my own adapter board. Works quite well.

I can now confirm this is working on a "WAMSLER WESTMINSTER QUATTRO 6"!

**Comment by aceindy** [comment]
i opened a telegram channel, that is probably easier to talk 😉
https://t.me/duepievo
