### ISSUE TITLE
Spotted a typo (and possibly a bug) in the code

### ISSUE THREAD

**Issue by davidebeatrici** [aceindy/Duepi_EVO#47]
While reading the code in order to learn how to make my own custom component, I spotted a typo: https://github.com/aceindy/Duepi_EVO/blob/629b9a8f1b0c254858f778d55ccc5461b7d3f9af/custom_components/duepi_evo/climate.py#L415

I'm pretty sure `HVACMode.OFFF` is supposed to be `HVACMode.OFF`.

The change was introduced in 79727f3e41b60674371625e53d63ea65591f7c5d.

**Comment by aceindy** [comment]
Thanks...corrected

**Comment by aceindy** [comment]
[davidebeatrici](https://github.com/davidebeatrici)
