### ISSUE TITLE
return-states

### ISSUE THREAD

**Issue by pascaltippelt** [aceindy/Duepi_EVO#6]
[EDIT: My fault, please ignore!]

**Comment by pascaltippelt** [comment]
There are more possebilitys for the state of the stove (replies after sending RD90005f&)
01020023 --> load wood
01030024 --> fire on
01040025 --> fire on + vent on

Together with 01010022 ("ignition") this is the whole ignition-process:
1) 0101
2) 0102
3) 0103
4) 0104

Maybe the states are also like the ones from https://github.com/pascaltippelt/Wamsler-IR-Remote ?

**Comment by aceindy** [comment]
Looks like there is a system:
RDx000yy
Up til RDA 
 Y = x56 + X 
after that it is
Y = x66 + X

These inquiries I've seen passing by:
RD000056 --> Flugas temperature (133 degs --> 0085002D (ignoring the last 2 digits)
RD100057 --> ambient temperature
RD200058
RD300059
RD40005A
RD70005D
RD80005E
RD90005F --> status
RDA00067 --> error code
RDB00068
RDD0006A
RDE0006B
RDF0006C

Makes me wonder if these are valid:
RD50005B
RD60005C
RDC00069
So far I haven't seen them anywhere....

Most of them can be matched from system overview (just didn't have the time yet to do so):
When loading the page, I can see the inquiries passing by one-by-one ;)
![image](https://user-images.githubusercontent.com/94692/107861239-d8db1500-6e44-11eb-9fe6-0aed54c587a3.png)

**Comment by pascaltippelt** [comment]
That looks very good. I will test them myself.

The duepi hardware was designed earlier to work with stoves that could also provide hot water. Maybe those unused areas have never been removed since then.

**Comment by mvroosmalen1970** [comment]
I've implemented the correct code for the main return states. This is working now. If needed we can implement the other sensors outside the climate sensor.
